#!/usr/bin/env python3

import datetime
import os
import sys

# Write a message to a given filepath and a backup path
def scribe(text, path, backup_path):
    # Gather formatted time string
    time = datetime.datetime.now().strftime("%I:%M%p on %A, %B %d, %Y")

    text = "=====\n" + time + ":\n" + text + "\n"

    # Write the data and backup if requested
    with open(path, "a+") as file:
        file.write(text)
        print("scribe wrote to %s" % path)
    if backup_path:
        with open(backup_path, "a+") as file:
            file.write(text)
            print("scribe wrote to %s" % backup_path)

if __name__ == "__main__":
    # If SCRIBE_PATH is not set, default to ~/scribe.txt
    path = os.environ.get('SCRIBE_PATH')
    if path is None:
        path = os.path.expanduser("~") + "/scribe.txt"
    backup_path = os.environ.get('SCRIBE_BACKUP')

    # Launch in interactive mode
    if len(sys.argv) == 1:
        scribe(sys.stdin.read(), path, backup_path)
    # Launch in argument mode
    else:
        scribe(sys.argv[1], path, backup_path)

